name: Update README Versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: python scripts/update_readme_versions.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add profile/README.md
          git commit -m "Update profile README with latest versions" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/GoozyaStudio/.github.git
          git push
